name: recipe_app
description: Апликација за рецепти со TheMealDB API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1

  # Firebase dependencies
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6

  # Local notifications - updated version
  flutter_local_notifications: ^18.0.1

  # State management за омилени
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true